#!/usr/bin/env python3
import argparse, socket
from typing import Any, Callable
from constants import *
from utilities import *

parser = argparse.ArgumentParser()
parser.add_argument('operation', action='store', type=str, 
    help='The operation to execute. Valid operations are ls, rm, rmdir, mkdir, cp, and mv') 
parser.add_argument('params', action='store', nargs='+', 
    help='Parameters for the given operation. Will be one or two paths and/or URLs.')

def __recv_full_msg(socket: socket.SocketType):
    msgText = recv_data(socket).decode('utf-8')
    # Read until end of response
    while msgText.count('\r\n') == 0:
        msgText += recv_data(socket)
    return msgText

def get_ctrl_response(s: socket.SocketType):
    res = __recv_full_msg(s)
    print(res)
    return res

def handle_login(socket: socket.SocketType, host:str , username:str, password: str) -> socket.SocketType:
    send_auth(socket)
    get_ctrl_response(socket)
    socket = encrypt_socket(socket, host)
    send_username(socket, username)
    get_ctrl_response(socket)
    send_password(socket, password)
    get_ctrl_response(socket)
    set_prot_buffer(socket)
    get_ctrl_response(socket)
    set_prot_level(socket)
    get_ctrl_response(socket)
    set_conn_type(socket)
    get_ctrl_response(socket)
    set_conn_mode(socket)
    get_ctrl_response(socket)
    set_conn_file(socket)
    get_ctrl_response(socket)
    return socket

def init_data_socket(ctrl_channel: socket.SocketType, ftp_operation: Callable[[socket.SocketType, str], Any] , remote_path: str, host: str) -> socket.SocketType:
    # STEP 1
    send_pasv(ctrl_channel)
    response = get_ctrl_response(ctrl_channel)
    data_channel_addr = parse_data_channel(response)
    # STEP 2
    ftp_operation(ctrl_channel, remote_path)
    # STEP 3
    data_socket = get_socket(data_channel_addr)
    # STEP 4
    res = get_ctrl_response(ctrl_channel)
    if is_response_error(res):
        print('Error opening data channel. CODE: {}'.format(res))
        print(remote_path)
        data_socket.close()
    else:
    # STEP 5
        data_socket = encrypt_socket(data_socket, host)
    return data_socket

def close_data_socket(data_socket: socket.SocketType, download=True):
    #Step 7, 8
    if not download:
        data_socket = data_socket.unwrap()
        data_socket.shutdown(socket.SHUT_WR)
    data_socket.close()
        
def handle_shutdown(socket: socket.SocketType, operation_success: bool):
    if operation_success:
        get_ctrl_response(socket)
    send_quit(socket)
    get_ctrl_response(socket)
    socket.close()

def handle_copy(ctrl_channel:socket.SocketType, local_path: str, remote_path: str, host: str, download: bool) -> bool:
    ftp_op = send_return if download else send_store
    data_socket = init_data_socket(ctrl_channel, ftp_op, remote_path, host)
    if data_socket.fileno() == -1:
        return False
    if download:
        file = get_file(local_path, 'wb')
        # STEP 6
        if file is None:
            return False
        data = recv_data(data_socket)
        while data:
            file.write(data)
            data = recv_data(data_socket)
        # STEP 7
        file.close()
        close_data_socket(data_socket, download)
    else:
        # STEP 6
        file = get_file(local_path, 'rb')
        if file is None:
            return False
        data = file.read(4096)
        while data:
            data_socket.sendall(data)
            data = file.read(4096)
        # STEP 7
        file.close()
        close_data_socket(data_socket, download)
    return True

def handle_list(ctrl_channel: socket.SocketType, remote_path:str, host:str):
    # STEP 1 - 5
    data_socket = init_data_socket(ctrl_channel, send_list, remote_path, host)
    if data_socket.fileno() == -1:
        return
    # STEP 6
    while True:
        data = recv_data(data_socket)
        if not data: break
        dir_list = data.decode('utf-8')
        print(dir_list)
    # STEP 7
    close_data_socket(data_socket)

def main(args):
    ftp_info = parse_ftp_paths(args.params)
    is_download = len(args.params) == 2 and args.params[0].startswith('ftps://')
    remote_path = ftp_info.get(REMOTE)
    local_path = ftp_info.get(LOCAL)
    operation = OPERATIONS_DICT.get(args.operation)
    socket = get_socket((ftp_info.get(HOST), ftp_info.get(PORT)))
    socket = handle_login(socket, host=ftp_info.get(HOST), username=ftp_info.get(USER), password=ftp_info.get(PASS))
    operation_success = True
   
    if operation == MKDIR:
        send_mkd(socket, remote_path)
    elif operation == RMDIR:
        send_rmd(socket, remote_path)
    elif operation == LS:
        operation_success = handle_list(ctrl_channel=socket, remote_path=remote_path, host=ftp_info.get(HOST)) 
    elif operation == CP:
        operation_success = handle_copy(ctrl_channel=socket, local_path=local_path, remote_path=remote_path, host=ftp_info.get(HOST), download=is_download)
    elif operation == RM:
        remote_path = ftp_info.get(REMOTE)
        send_del(socket, remote_path)
    elif operation == MV:
        operation_success = handle_copy(ctrl_channel=socket, local_path=local_path, remote_path=remote_path, host=ftp_info.get(HOST), download=is_download)
        if operation_success and is_download:
            send_del(socket, remote_path)
        elif operation_success:
            try:
                os.remove(local_path)
            except OSError:
                print('No local file to remove after mv')
                
    handle_shutdown(socket, operation_success)
    
if __name__ == '__main__':
    args = parser.parse_args()
    if not valid_operation(args):
        print('Invalid operation received: {}'.format(args.operation))
        quit()
    main(args)
