#!/usr/bin/env python3

import argparse, socket, time, json, select, struct, math
import re
from re import split

#DEBUG = True
DEBUG = False

parser = argparse.ArgumentParser(description='route packets')
parser.add_argument('asn', type=int, help="AS Number")
parser.add_argument('networks', metavar='networks', type=str, nargs='+', help="networks")
args = parser.parse_args()

##########################################################################################

# Message Fields
TYPE = "type"
SRCE = "src"
DEST = "dst"
MESG = "msg"
TABL = "table"

# Message Types
DATA = "data"
DUMP = "dump"
UPDT = "update"
RVKE = "revoke"
NRTE = "no route"

# Update Message Fields
NTWK = "network"
NMSK = "netmask"
ORIG = "origin"
LPRF = "localpref"
APTH = "ASPath"
SORG = "selfOrigin"

# internal route info
CUST = "cust"
PEER = "peer"
PROV = "prov"


##########################################################################################

class Router:

    routes = None
    updates = None
    relations = None
    sockets = None

    def __init__(self, networks, asn):
        self.routes = []
        self.updates = []
        self.relations = {}
        self.sockets = {}
        self.asn = asn
        for relationship in networks:
            network, relation = relationship.split("-")
            # if DEBUG: 
            print("Starting socket for", network, relation)
            self.sockets[network] = socket.socket(socket.AF_UNIX, socket.SOCK_SEQPACKET)
            self.sockets[network].setblocking(0)
            self.sockets[network].connect(network)
            self.relations[network] = relation
        return

    def __send_packet(self, packet, dest):
        socket = self.sockets[dest]
        socket.send(json.dumps(packet).encode())

    def lookup_routes(self, daddr):
        """ Lookup all valid routes for an address """
        outroutes = []
        split_addr = [int(val) for val in daddr.split('.')]
        print(f'DEST: {daddr}\n')
        for route in self.routes:
            print(f'CHECKING ROUTE: {route}\n')
            netmask = [int(nmsk) for nmsk in route[NMSK].split('.')]
            network = [int(ntwk) for ntwk in route[NTWK].split('.')]

            res = True
            for ii in range(len(netmask)):
                if netmask[ii] == 255:
                    res = res and split_addr[ii] == network[ii]
            if res and split_addr[3] in range(1, 255):
                outroutes.append(route)
        print(f'OUTROUTES: {outroutes}\n')

        return outroutes

    def get_shortest_as_path(self, routes):
        """ select the route with the shortest AS Path """
        # TODO
        outroutes = []
        return outroutes
            
    def get_highest_preference(self, routes):
        """ select the route with the highest localpref """
        # TODO
        outroutes = routes
        if len(outroutes) > 1:
            print(len(outroutes))
            r1 = outroutes[0][LPRF]
            r2 = outroutes[1][LPRF]
            if r1 > r2:
                del outroutes[1]
            elif r2 > r1:
                del outroutes[0]
            return outroutes
            
        outroutes = []
        return outroutes
         
    def get_self_origin(self, routes):
        """ select self originating routes """
        outroutes = []
        for route in routes:
            print(route[SORG])
            if route[SORG]:
                outroutes.append(route)
        return outroutes

    def get_origin_routes(self, routes):
        """ select origin routes: IGP > EGP > UNK """
        # TODO
        outroutes = []
        return outroutes

    def filter_relationships(self, srcif, routes):
        """ Don't allow Peer->Peer, Peer->Prov, or Prov->Peer forwards """
        outroutes = []
        return outroutes

    def get_route(self, srcif, daddr) -> socket.SocketType:
        """	Select the best route for a given address	"""
        peer = None
        routes = self.lookup_routes(daddr)
        # Rules go here
        if routes:
            # 1. Highest Preference
            # routes = self.get_highest_preference(routes)
            # 2. Self Origin
            # routes = self.get_self_origin(routes)
            # 3. Shortest ASPath
            # routes = self.get_shortest_as_path(routes)
            # 4. IGP > EGP > UNK
            # routes = self.get_origin_routes(routes)
            # 5. Lowest IP Address
            # TODO
            # Final check: enforce peering relationships
            # routes = self.filter_relationships(srcif, routes)
            peer = routes[0][PEER] if routes else None 
            print(f'Peer: {peer}')
        return peer

    def forward(self, srcif, packet):
        """	Forward a data packet	"""
        print(f'FORWARD: {packet}\n')
        peer = self.get_route(srcif, packet[DEST])
        if peer:
            # TODO: refactor get_route to return Peer
            self.__send_packet(packet, peer)
            return True
        # NO ROUTE
        temp = srcif.split('.')
        temp[3] = '1'
        new_src = '.'.join(temp)
        new_dest = packet[SRCE]

        packet[SRCE] = new_src
        packet[DEST] = new_dest
        packet[TYPE] = NRTE
        packet[MESG] = {}
        print(f'{packet} NO ROUTE')

        socket = self.sockets[srcif]
        socket.send(json.dumps(packet).encode())
        # self.__send_packet(packet, packet[SRCE])
        return False

    def coalesce(self):
        """	coalesce any routes that are right next to each other	"""
        # TODO (this is the most difficult task, save until last)
        return False

    def update(self, srcif, packet):
        """	handle update packets	"""
        # print(packet)
        msg = packet[MESG]
        # print(msg)
        print(f'UPDATE: {packet}')
        self.updates.append(msg)
        route_entry = {NTWK: msg[NTWK], NMSK: msg[NMSK], PEER: srcif, LPRF: msg[LPRF],
                        APTH: msg[APTH], ORIG: msg[ORIG], SORG: msg[SORG]}
        self.routes.append(route_entry)
        msg[APTH].append(self.asn)
        self.__send_updates(srcif, packet)
        return True

    def __send_updates(self, srcif, packet):
        """ Handle forwarding route announcements """
        networks = self.relations.keys()
        update_customers = self.relations[srcif] == PEER or self.relations[srcif] == PROV
        for network in networks:
            if network == srcif:
                # Don't send update to self
                continue
            if update_customers and (self.relations[network] == PEER or self.relations[network] == PROV):
                # only update this routers customers
                continue
            # Send updates to neighbors
            temp = network.split('.')
            temp[3] = '1'
            new_src = '.'.join(temp)
            new_dest = network

            print(f'Update Packet Before: {packet}')
            packet[SRCE] = new_src
            packet[DEST] = new_dest
            print(f'Update Packet After: {packet}')
            self.__send_packet(packet, new_dest)
        return True

    def revoke(self, packet):
        """	handle revoke packets	"""
        # TODO
        return True

    def dump(self, packet):
        """	handles dump table requests	"""
        old_src = packet[SRCE]
        packet[SRCE] = packet[DEST]
        packet[DEST] = old_src
        packet[TYPE] = TABL
        msg = []
        for route in self.routes:
            temp = {NTWK: route[NTWK], NMSK: route[NMSK], PEER: route[PEER]}
            msg.append(temp)
        packet[MESG] = msg
        print(f'{MESG}: {msg}')
        print(f'{TABL}: {self.routes}')
        self.__send_packet(packet, old_src)
        return True

    def handle_packet(self, srcif, packet):
        """	dispatches a packet """
        if packet[TYPE] == UPDT:
            return self.update(srcif, packet)
        elif packet[TYPE] == DATA:
            return self.forward(srcif, packet)
        elif packet[TYPE]  == DUMP:
            return self.dump(packet)
        return False

    def send_error(self, conn, msg):
        """ Send a no_route error message """
        # TODO
        return

    def run(self):
        while True:
            socks = select.select(self.sockets.values(), [], [], 0.1)[0]
            for conn in socks:
                try:
                    k = conn.recv(65535)
                except:
                    # either died on a connection reset, or was SIGTERM's by parent
                    return
                if k:
                    for sock in self.sockets:
                        if self.sockets[sock] == conn:
                            srcif = sock
                    msg = json.loads(k)
                    if not self.handle_packet(srcif, msg):
                        self.send_error(conn, msg)
                else:
                    return
        return

if __name__ == "__main__":
    router = Router(args.networks, args.asn)
    router.run()
